' Сервис управления. Приём данных. Диаграмма последовательности.

@startuml

Title "Сервис управления. Приём данных. Диаграмма последовательности."

queue Queue as "Очередь сообщений помещений"
participant Input as "Компонент приема данных"
participant Core as "Компонент выработки управления"
participant Cache as "Кэш контекстов датчиков"
participant Repo as "Компонент связи с БД"
database DB

Queue ->> Input : Новые показания датчика ID=NNN
Input ->> Core : Новые показания датчика ID=NNN
alt
    Core -> Cache: Загрузить и обновить контекст датчика ID=NNN
else
    Core -> Repo: Загрузить контекст датчика ID=NNN
    Repo -> DB: Загрузить контекст датчика ID=NNN
    Core -> Cache: Сохранить и обновить контекст датчика ID=NNN
end
Core -> Core: Вычислить управляющее воздействие
Queue <<- Core: Направить управляющее воздействие

Input ->> Repo : Новые показания датчика ID=NNN
Repo -> DB: Обновить контекст датчика ID=NNN
@enduml