' ER-диаграмма

@startuml

Title "Тёплый дом. Диаграмма сущностей"

entity Пользователь {
* идентификатор: string
--
* ФИО: string
паспортные_данные: string
телефон: string
email: string
}

entity Настройки_пользователя {
* идентификатор: string
--
настройки: string
}

entity Помещение {
* идентификатор: string
--
* адрес: string
}

entity Устройство {
* идентификатор: string
--
* наименование: string
* серийный_номер: string
* тип: [вход/выход/двусторонний]
* протокол: string
}

entity Контекст_устройства {
* идентификатор: string
--
целевое_значение: string
}

entity Показания {
* идентификатор_устройства: string
* дата_время: timestamp
--
показания: string
}

Пользователь ||-right-o{ Помещение : владеет
Пользователь ||-down-|| Настройки_пользователя
Помещение ||-right-o{ Устройство : содержит
Устройство }|--o| Устройство : управляет
Устройство ||-down-|| Контекст_устройства
Контекст_устройства ||-down-o{ Показания: последние N показаний

@enduml